---
  extends:
    - 'plugin:@typescript-eslint/recommended'
    - 'prettier'
    - 'prettier/@typescript-eslint'
    - 'plugin:prettier/recommended'
  plugins:
    - '@typescript-eslint'
  env:
    node: true
    es6: true
  parser: '@typescript-eslint/parser'
  parserOptions:
    ecmaVersion: 2018
    sourceType: 'module'
    project: './tsconfig.json'
  rules:
    linebreak-style: 'off'
    prettier/prettier:
      - 'error'
      -
        endOfLine: 'auto'
    '@typescript-eslint/explicit-function-return-type': 'off'
    '@typescript-eslint/no-explicit-any': 'off'
    '@typescript-eslint/explicit-module-boundary-types': 'off'
    '@typescript-eslint/no-unused-vars': 'off'
    no-console: 'off'
